### PR TITLE
Request to merge Milestone 2 to Development branch

### PR DESCRIPTION
**Pull request by Haywhizzz**
In this Pull Request, we have implemented the following into the project

- Users can now send friendship requests to other users

- Users can see a button “Send friend request” next to the name of a user who isn't already friends with them on the users’ list

- Users can now decide to accept or decline friendship requests

- Users can see pending requests sent by other users

- Tests have been written for the User and Post models

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Haywhizzz and @Abidoyinsola1, great job with this project :+1: However, there are comments we need to address so we can approve the project. Kindly check the comments below:
- `Database` is not configured properly. After running the following commands in the README file `rails db:create` `rails db:migrate` I came across this error as in the screenshot below
r1
Kindly fix this
- Also, there is inconsistency with the `ruby versions` the `ruby-version` file is `2.7.0`, gemfile is `2.7.1` and the README has `2.6.3` under prerequisite. Let us fix it
- Let us stay focus on the `Friendship v1` requirements
- Based on the error with database configuration, I was unable to test the functionality of the app

[Optional]
- Kindly read about then+1 query problem [here](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5)

Kindly submit another code review once these are resolved :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, I am experiencing the same errors from the previous reviews. Kindly fix this especially with the database.
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by Haywhizzz** [comment]
For this project you don't need to run the rails db:create and migrate command again
those were for setting up the database which we already did when we setup the project

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
